---
- hosts: localhost
  become: yes
  vars_files:
    - secrets.yml
    - ssh_keys.yml
  tasks:
    # Base package installation
    - name: Install base packages
      apt:
        name:
          - htop
          - gpustat
          - nano
          - ffmpeg
          - iputils-ping
          - btop
          - samba
          - transmission-daemon
          - curl
          - git
          - python3-full
          - whois
          - traceroute
          - gcc
          - make
        state: present
        update_cache: yes

    # SSH key setup
    - name: Create .ssh directory
      file:
        path: /home/avelis/.ssh
        state: directory
        mode: "0700"
        owner: avelis
        group: avelis

    - name: Add SSH authorized keys
      lineinfile:
        path: /home/avelis/.ssh/authorized_keys
        line: "{{ item }}"
        create: yes
        owner: avelis
        group: avelis
        mode: "0600"
      loop: "{{ ssh_keys }}"

    # Bashrc customization
    - name: Add aliases and export to bashrc
      lineinfile:
        path: /home/avelis/.bashrc
        line: "{{ item }}"
      loop:
        - 'alias ls="ls -lhAp --color=always"'
        - 'alias ll="ls -lhAp --color=always"'
        - 'alias update="sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y"'
        - 'alias nvtop="gpustat -a -i 1"'
        - 'export PATH="$PATH:/home/avelis/.local/bin"'

    # Samba setup
    - name: Setup Samba user
      user:
        name: samba
        state: present
        password: "{{ samba_password }}"

    - name: Configure Samba shares
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [data]
             path = /mnt/data
             read only = no
             valid users = samba

    - name: Ensure Samba directory exists
      file:
        path: /mnt/data
        state: directory
        owner: avelis
        group: samba
        mode: "0777"

    # Fstab configuration
    - name: Ensure fstab entry for /mnt/data
      mount:
        path: /mnt/data
        src: /dev/mapper/vg_data-lv_data
        fstype: ext4
        opts: defaults
        state: mounted

    # Transmission config
    - name: Check if Transmission is installed
      package:
        name: transmission-daemon
        state: present
      register: transmission_installed

    - name: Stop Transmission Daemon
      systemd:
        name: transmission-daemon
        state: stopped
      when: transmission_installed.changed

    - name: Update Transmission settings
      copy:
        src: transmission_settings.json
        dest: /etc/transmission-daemon/settings.json
        owner: debian-transmission
        group: debian-transmission
        mode: "0644"
      notify: Restart Transmission
      when: transmission_installed.changed

  handlers:
    - name: Restart Transmission
      systemd:
        name: transmission-daemon
        state: restarted
