---
- hosts: localhost
  become: yes
  vars_files:
    - secrets.yaml
    - ssh_keys.yaml
  tasks:
    # Base package installation
    - name: Install base packages
      apt:
        name:
          - htop
          - gpustat
          - nano
          - ffmpeg
          - iputils-ping
          - btop
          - samba
          - transmission-daemon
          - curl
          - git
          - python3-full
          - whois
          - traceroute
          - gcc
          - make
        state: present
        update_cache: yes

    # SSH key setup
    - name: Create .ssh directory
      file:
        path: /home/avelis/.ssh
        state: directory
        mode: '0700'
        owner: avelis
        group: avelis

    - name: Add SSH authorized keys
      lineinfile:
        path: /home/avelis/.ssh/authorized_keys
        line: "{{ item }}"
        create: yes
        owner: avelis
        group: avelis
        mode: '0600'
      loop: "{{ ssh_keys }}"

    # Bashrc customization
    - name: Add aliases and export to bashrc
      lineinfile:
        path: /home/avelis/.bashrc
        line: "{{ item }}"
      loop:
        - 'alias ls="ls -lhAp --color=always"'
        - 'alias ll="ls -lhAp --color=always"'
        - 'alias update="sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y"'
        - 'alias nvtop="gpustat -a -i 1"'
        - 'export PATH="$PATH:/home/avelis/.local/bin"'

    # Samba setup
    - name: Setup Samba user
      user:
        name: samba
        state: present
        password: "{{ samba_password }}"
        
    - name: Configure Samba shares
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [data]
             path = /mnt/data
             read only = no
             valid users = samba

    - name: Ensure Samba directory exists
      file:
        path: /mnt/data
        state: directory
        owner: avelis
        group: samba
        mode: '0777'

    # Fstab configuration
    - name: Ensure fstab entry for /mnt/data
      mount:
        path: /mnt/data
        src: /dev/mapper/vg_data-lv_data
        fstype: ext4
        opts: defaults
        state: mounted

    # Install and configure Emby
    #- name: Download Emby
    #  get_url:
    #    url: https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.8.0/emby-server-deb_4.8.8.0_amd64.deb
    #    dest: /tmp/emby-server-deb_4.8.8.0_amd64.deb

    #- name: Install Emby
    #  apt:
    #    deb: /tmp/emby-server-deb_4.8.8.0_amd64.deb

    #- name: Setup Emby directories
    #  file:
    #    path: "{{ item.path }}"
    #    state: directory
    #    owner: emby
    #    group: emby
    #    mode: '0755'
    #  loop:
    #    - { path: "/var/lib/emby/metadata" }
    #    - { path: "/var/lib/emby/temp" }
    #    - { path: "/mnt/data/emby/backup" }

    # Transmission config
    - name: Stop Transmission Daemon
      systemd:
        name: transmission-daemon
        state: stopped

    - name: Update Transmission settings
      copy:
        dest: /etc/transmission-daemon/settings.json
        content: |
          {
            "alt-speed-down": 50,
            "alt-speed-time-begin": 540,
            "alt-speed-time-day": 127,
            "alt-speed-time-enabled": false,
            "alt-speed-time-end": 1020,
            "alt-speed-up": 50,
            "announce-ip": "",
            "announce-ip-enabled": false,
            "anti-brute-force-enabled": false,
            "anti-brute-force-threshold": 100,
            "bind-address-ipv4": "0.0.0.0",
            "bind-address-ipv6": "::",
            "blocklist-enabled": false,
            "blocklist-url": "",
            "cache-size-mb": 128,
            "default-trackers": "",
            "dht-enabled": true,
            "download-dir": "/mnt/data/Torrents/Complete",
            "download-limit": 100,
            "download-limit-enabled": 0,
            "download-queue-enabled": true,
            "download-queue-size": 5,
            "encryption": 1,
            "idle-seeding-limit": 30,
            "idle-seeding-limit-enabled": false,
            "incomplete-dir": "/mnt/data/Torrents/Downloading",
            "incomplete-dir-enabled": true,
            "lpd-enabled": true,
            "max-peers-global": 200,
            "message-level": 2,
            "peer-congestion-algorithm": "",
            "peer-limit-global": 200,
            "peer-limit-per-torrent": 50,
            "peer-port": 51413,
            "peer-port-random-high": 65535,
            "peer-port-random-low": 49152,
            "peer-port-random-on-start": false,
            "peer-socket-tos": "le",
            "pex-enabled": true,
            "port-forwarding-enabled": false,
            "preallocation": 1,
            "prefetch-enabled": true,
            "queue-stalled-enabled": true,
            "queue-stalled-minutes": 30,
            "ratio-limit": 2,
            "ratio-limit-enabled": false,
            "rename-partial-files": false,
            "rpc-authentication-required": true,
            "rpc-bind-address": "::",
            "rpc-enabled": true,
            "rpc-host-whitelist": "192.168.*.*,fe80::*",
            "rpc-host-whitelist-enabled": true,
            "rpc-password": "{{ rpc_password }}",
            "rpc-port": 9091,
            "rpc-socket-mode": "0750",
            "rpc-url": "/transmission/",
            "rpc-username": "avelis",
            "rpc-whitelist": "192.168.*.*,fe80::*",
            "rpc-whitelist-enabled": false,
            "scrape-paused-torrents-enabled": true,
            "script-torrent-added-enabled": false,
            "script-torrent-added-filename": "",
            "script-torrent-done-enabled": false,
            "script-torrent-done-filename": "",
            "script-torrent-done-seeding-enabled": false,
            "script-torrent-done-seeding-filename": "",
            "seed-queue-enabled": false,
            "seed-queue-size": 10,
            "speed-limit-down": 100,
            "speed-limit-down-enabled": false,
            "speed-limit-up": 100,
            "speed-limit-up-enabled": false,
            "start-added-torrents": true,
            "tcp-enabled": true,
            "torrent-added-verify-mode": "fast",
            "trash-original-torrent-files": false,
            "umask": "022",
            "upload-limit": 100,
            "upload-limit-enabled": 0,
            "upload-slots-per-torrent": 8,
            "utp-enabled": true
        }
      notify: Restart Transmission

  handlers:
    - name: Restart Transmission
      systemd:
        name: transmission-daemon
        state: restarted
