- hosts: localhost
  become: yes
  vars_files:
    - secrets.yml
    - ssh_keys.yml
  tasks:
    # Packages
    - name: Install base packages
      apt:
        name:
          - htop
          - gpustat
          - nano
          - ffmpeg
          - iputils-ping
          - btop
          - samba
          - transmission-daemon
          - curl
          - git
          - python3-full
          - whois
          - traceroute
          - gcc
          - make
        state: present
        update_cache: yes
    # SSH
    - name: Add SSH authorized keys
      authorized_key:
        user: avelis
        key: "{{ item }}"
      loop: "{{ ssh_keys }}"
    # Bashrc
    - name: Update BASHRC
      lineinfile:
        path: /home/avelis/.bashrc
        line: "{{ item }}"
        create: yes
        insertafter: EOF
      loop:
        - 'alias ls="ls -lhAp --color=always"'
        - 'alias ll="ls -lhAp --color=always"'
        - 'alias update="sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y"'
        - 'alias nvtop="gpustat -a -i 1"'
        - 'export PATH="$PATH:/home/avelis/.local/bin"'
    # Samba
    - name: Create Samba user
      command: "echo -e '{{ samba_password }}\n{{ samba_password }}' | smbpasswd -a samba"
      args:
        creates: /var/lib/samba/private/passdb.tdb
    - name: Configure Samba share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [data]
             path = /mnt/data
             read only = no
             valid users = samba
    - name: Set Samba directory
      file:
        path: /mnt/data
        state: directory
        owner: avelis
        group: samba
        mode: "0777"
    # Fstab
    - name: Edit FSTAB
      mount:
        path: /mnt/data
        src: /dev/mapper/vg_data-lv_data
        fstype: ext4
        opts: defaults
        state: mounted
    # Transmission
    - name: Stop Transmission Daemon
      systemd:
        name: transmission-daemon
        state: stopped
    - name: Set Transmission settings
      template:
        src: transmission_settings.json
        dest: /etc/transmission-daemon/settings.json
        owner: debian-transmission
        group: debian-transmission
        mode: "0644"
      notify: Restart Transmission
    - name: Enable Transmission Daemon
      systemd:
        name: transmission-daemon
        enabled: yes
    # NVIDIA
    - name: Install NVIDIA driver
      apt:
        name: "nvidia-driver-550"
        state: present
        update_cache: yes
      notify: Reboot system
  handlers:
    - name: Reboot system
      reboot:
        msg: "Rebooting system to load NVIDIA driver"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 5
        post_reboot_delay: 10
    - name: Restart Transmission
      systemd:
        name: transmission-daemon
        state: restarted
