- hosts: embyone
  become: yes
  vars_files:
    - secrets.yml
    - ssh_keys.yml
  tasks:
    # Update and Upgrade APT Packages
    - name: Update and Upgrade APT Packages
      apt:
        update_cache: yes
        upgrade: dist
      register: apt_update_upgrade

    # Packages
    - name: Install Base Packages
      apt:
        name:
          - htop
          - gpustat
          - nano
          - ffmpeg
          - iputils-ping
          - btop
          - samba
          - transmission-daemon
          - curl
          - git
          - python3-full
          - whois
          - traceroute
          - gcc
          - make
          - mate-desktop-environment
          - cool-retro-term
          - lightdm
        state: present
        update_cache: yes

    # SSH
    - name: Add SSH Keys
      authorized_key:
        user: avelis
        key: "{{ item }}"
      loop: "{{ ssh_keys }}"

    # Bashrc
    - name: Update BASHRC
      lineinfile:
        path: /home/avelis/.bashrc
        line: "{{ item }}"
        create: yes
        insertafter: EOF
      loop:
        - 'alias ls="ls -lhAp --color=always"'
        - 'alias ll="ls -lhAp --color=always"'
        - 'alias update="sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y"'
        - 'alias nvtop="gpustat -a -i 1"'
        - 'export PATH="$PATH:/home/avelis/.local/bin"'

    # Samba
    - name: Create Samba Group
      group:
        name: samba
        state: present

    - name: Create Samba User
      user:
        name: samba
        comment: Samba user
        groups: samba
        append: yes

    - name: Create Samba Password
      command: "echo -e '{{ samba_password }}\n{{ samba_password }}' | smbpasswd -a samba"
      args:
        creates: /var/lib/samba/private/passdb.tdb

    - name: Configure Samba Share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [data]
             path = /mnt/data
             read only = no
             valid users = samba

    - name: Set Samba Directory
      file:
        path: /mnt/data
        state: directory
        owner: avelis
        group: samba
        mode: "0777"

    # Fstab
    - name: Edit FSTAB
      mount:
        path: /mnt/data
        src: /dev/mapper/vg_data-lv_data
        fstype: ext4
        opts: defaults
        state: mounted

    # Transmission
    - name: Stop Transmission Daemon
      systemd:
        name: transmission-daemon
        state: stopped

    - name: Set Transmission Settings
      template:
        src: transmission_settings.json
        dest: /etc/transmission-daemon/settings.json
        owner: debian-transmission
        group: debian-transmission
        mode: "0644"

    - name: Enable Transmission Daemon
      systemd:
        name: transmission-daemon
        enabled: yes

    # Set up MATE to log in automatically
    - name: Configure LightDM for auto-login
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        line: "autologin-user=avelis"
        create: yes

    # Create a script to launch cool-retro-term in full-screen
    - name: Create cool-retro-term launcher script
      copy:
        dest: /home/avelis/start_cool_retro_term.sh
        content: |
          #!/bin/bash
          cool-retro-term --fullscreen
        mode: '0755'
        owner: avelis
        group: avelis

    # Ensure autostart directory exists
    - name: Create autostart directory
      file:
        path: /home/avelis/.config/autostart
        state: directory
        owner: avelis
        group: avelis
        mode: '0755'

    # Autostart cool-retro-term
    - name: Create autostart entry for cool-retro-term
      copy:
        dest: /home/avelis/.config/autostart/cool-retro-term.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Exec=/home/avelis/start_cool_retro_term.sh
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name=Cool Retro Term
          Comment=Launch Cool Retro Term on startup
        mode: '0644'
        owner: avelis
        group: avelis

    # NVIDIA
    - name: Install NVIDIA Driver
      apt:
        name: "nvidia-driver-535-server"
        state: present
        update_cache: yes
      notify: Reboot System

    # Reboot if packages were upgraded
    - name: Reboot if packages were upgraded
      reboot:
        msg: "Rebooting system to apply upgrades..."
      when: apt_update_upgrade.changed
