- hosts: embyone
  become: yes
  vars_files:
    - secrets.yml
  
  tasks:
    # SSH
    - name: Create SSH Directory
      file:
        path: /home/avelis/.ssh
        state: directory
        owner: avelis
        group: avelis
        mode: '0700'

    - name: Add Gaming-PC SSH Key
      authorized_key:
        user: avelis
        key: "{{ item }}"
      loop: "{{ ssh_keys }}"

    - name: Add Pi-Star SSH Key
      authorized_key:
        user: avelis
        state: present
        key: "{{ lookup('file', '/home/pi-star/.ssh/id_rsa.pub') }}"
      delegate_to: embyone

    - name: Add User To Sudoers
      lineinfile:
        path: /etc/sudoers
        line: 'avelis ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
    
    # APT
    - name: Update & Upgrade APT
      apt:
        update_cache: yes
        upgrade: dist
      register: apt_update_upgrade

    # Packages
    - name: Install Base Packages
      apt:
        name:
          - xorg
          - lightdm
          - mate-desktop-environment
          - mate-session-manager
          - mate-control-center
          - xserver-xorg-core
          - xinit
          - xserver-xorg-video-nouveau
          - htop
          - gpustat
          - nano
          - ffmpeg
          - iputils-ping
          - btop
          - samba
          - transmission-daemon
          - curl
          - git
          - python3-full
          - whois
          - traceroute
          - gcc
          - make
          - cool-retro-term
        state: present
        update_cache: yes

    # NVIDIA
    - name: Install NVIDIA Driver
      apt:
        name: "nvidia-driver-535-server"
        state: present
        update_cache: yes
      register: nvidia_install

    # Emby
    - name: Confirm Emby
      shell: dpkg -l | grep emby-server
      register: emby_installed
      ignore_errors: yes
      changed_when: false

    - name: Download Emby
      get_url:
        url: https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.9.0/emby-server-deb_4.8.9.0_amd64.deb
        dest: /tmp/emby-server-deb_4.8.9.0_amd64.deb
      when: emby_installed.rc != 0

    - name: Install Emby
      apt:
        deb: /tmp/emby-server-deb_4.8.9.0_amd64.deb
      when: emby_installed.rc != 0

    # Reboot if necessary
    - name: Reboot Conditionally
      reboot:
        msg: "Rebooting system..."
      when: apt_update_upgrade.changed or nvidia_install.changed or emby_installed.rc != 0

    # Bashrc
    - name: Update BASHRC
      lineinfile:
        path: /home/avelis/.bashrc
        line: "{{ item }}"
        create: yes
        insertafter: EOF
      loop:
        - 'alias ls="ls -lhAp --color=always"'
        - 'alias ll="ls -lhAp --color=always"'
        - 'alias update="sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y"'
        - 'alias nvtop="gpustat -a -i 1"'
        - 'export PATH="$PATH:/home/avelis/.local/bin"'

    # Samba
    - name: Create Samba User
      user:
        name: "{{ item.username }}"
        state: present
      with_items:
        - "{{ samba_users }}"

    - name: Set Samba Password
      shell: "printf '{{ item.password }}\n{{ item.password }}\n' | smbpasswd -a {{ item.username }}"
      with_items:
        - "{{ samba_users }}"
      tags: smbpasswd
      no_log: false

    - name: Set Samba Directory
      file:
        path: /mnt/data
        state: directory
        owner: samba
        group: samba
        mode: "0777"

    - name: Configure Samba Share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [data]
            path = /mnt/data
            valid users = {{ samba_users | map(attribute='username') | join(',') }}
            read only = no
            browsable = yes
            create mask = 0777
            directory mask = 0777

    # Fstab
    - name: Edit FSTAB
      mount:
        path: /mnt/data
        src: /dev/mapper/vg_data-lv_data
        fstype: ext4
        opts: defaults
        state: mounted

    # Transmission
    - name: Stop Transmission Daemon
      systemd:
        name: transmission-daemon
        state: stopped

    - name: Update Transmission Settings #test here - all above success
      template:
        src: transmission_settings.json
        dest: /etc/transmission-daemon/settings.json
        owner: debian-transmission
        group: debian-transmission
        mode: "0644"

    - name: Enable Transmission Daemon
      systemd:
        name: transmission-daemon
        enabled: yes

    - name: Change Transmission Type
      lineinfile:
        path: /lib/systemd/system/transmission-daemon.service
        regexp: '^Type=notify'
        line: 'Type=simple'
        state: present

    # LightDM
    - name: Update LightDM Config
      copy:
        dest: /etc/lightdm/lightdm.conf
        content: |
          [Seat:*]
          autologin-user=avelis
          autologin-user-timeout=0
        mode: '0644'

    - name: Enable LightDM
      systemd:
        name: lightdm
        enabled: yes

    - name: Start LightDM
      systemd:
        name: lightdm
        state: started

    - name: Set Default GUI
      command: systemctl set-default graphical.target

    - name: Create Term Config Directory
      file:
        path: /home/avelis/.config/cool-retro-term
        state: directory
        owner: avelis
        group: avelis
        mode: '0755'

    - name: Copy Term Profile
      copy:
        src: matrix.json
        dest: /home/avelis/.config/cool-retro-term/matrix.json
        owner: avelis
        group: avelis
        mode: '0644'

    - name: Create Autostart Directory
      file:
        path: /home/avelis/.config/autostart
        state: directory
        owner: avelis
        group: avelis
        mode: '0755'

    - name: Create Term Autostart
      copy:
        dest: /home/avelis/.config/autostart/cool-retro-term.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Exec=cool-retro-term --fullscreen
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name=Cool Retro Term
          Comment=Launch cool-retro-term on desktop login
        owner: avelis
        group: avelis
        mode: '0644'

    # Directories
    - name: Set Emby Directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: emby
        group: emby
        mode: '0755'
      loop:
        - { path: "/mnt/data/emby" }
        - { path: "/var/lib/emby/metadata" }
        - { path: "/var/lib/emby/temp" }
        - { path: "/mnt/data/emby/backup" }

    - name: Set Torrent Directories
      file:
        path: /mnt/data/Torrents
        state: directory
        owner: debian-transmission
        group: debian-transmission
        recurse: yes

    # Reboot
    - name: Reboot
      reboot:
        msg: "Rebooting system..."
