rpc_password: ''
ansible_ssh_pass: ''
ansible_become_pass: ''
mssql_sa_password: ''
linux_user: ''
samba_users:
  - username: ''
    password: ''
ssh_keys:
  - ''
vars:
  emby_version: 4.8.9.0
  emby_deb_url: "https://github.com/MediaBrowser/Emby.Releases/releases/download/{{ emby_version }}/emby-server-deb_{{ emby_version }}_amd64.deb"
  emby_deb_path: "/tmp/emby-server-deb_{{ emby_version }}_amd64.deb"